### ISSUE TITLE
Wanneer wordt de module geupdate?

### ISSUE THREAD

**Issue by yvonn** [ICEPAY/OpenCart-2.x#4]
Helaas is de update veroudert. Er zijn inmiddels al drie nieuwe versies. Wanneer wordt de module geupdate?

**Comment by tsygankov** [comment]
Hi Yvonn,

At the moment the ICEPAY module for OpenCart is not compatible with OpenCart v.2.3.x. We will estimate the development effort and let you know the approximate beta release date.
